language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.2" ]]; then composer require --dev phpstan/phpstan --prefer-dist --update-with-dependencies; fi
  - travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml
  - if [[ "${TRAVIS_PHP_VERSION}" == "7.2" ]]; then vendor/bin/phpstan analyse -l 6 src lu-bin; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
