#!/usr/bin/env php
<?php

if (is_file(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use SobanVuex\LumenBin\Console\Application;

$app = new Application('LumenBin\\Console', '0.0.1');
$app
    ->loadCommands()
    ->run()
;
